baseURL: 'https://api.covidbahamas.app/'
languageCode: en-uk
title: COVID-19 API Bahamas

upload_dir: static/uploads
public_path: /uploads

disableKinds:
  - taxonomy
  - taxonomyTerm
  - categories

outputs:
  page:
    - HTML
    - json
    # - CSV
  section:
    - HTML
    - json
    # - CSV
  home:
    - HTML


# paginate: 2




